// Code generated by Slice Machine. DO NOT EDIT.

import ContactForm from "./ContactForm";
import CostumeDetails from "./CostumeDetails";
import HeadingWithText from "./HeadingWithText";
import Image from "./Image";
import ImageGallery from "./ImageGallery";
import Quote from "./Quote";
import Text from "./Text";

export {
  ContactForm,
  CostumeDetails,
  HeadingWithText,
  Image,
  ImageGallery,
  Quote,
  Text,
};

export const components = {
  contact_form: ContactForm,
  gallery_image: CostumeDetails,
  heading_with_text: HeadingWithText,
  image: Image,
  image_gallery: ImageGallery,
  quote: Quote,
  text: Text,
};
