// Code generated by Slice Machine. DO NOT EDIT.

import AboutMeShort from './AboutMeShort';
import ContactForm from './ContactForm';
import CostumeDetails from './CostumeDetails';
import HeadingWithText from './HeadingWithText';
import Image from './Image';
import ImageGallery from './ImageGallery';
import InstagramFeed from './InstagramFeed';
import LatestCostumes from './LatestCostumes';
import Quote from './Quote';
import Slider from './Slider';
import Text from './Text';

export {
	AboutMeShort,
	ContactForm,
	CostumeDetails,
	HeadingWithText,
	Image,
	ImageGallery,
	InstagramFeed,
	LatestCostumes,
	Quote,
	Slider,
	Text,
};

export const components = {
	about_me_short: AboutMeShort,
	contact_form: ContactForm,
	gallery_image: CostumeDetails,
	heading_with_text: HeadingWithText,
	image: Image,
	image_gallery: ImageGallery,
	instagram_feed: InstagramFeed,
	latest_costumes: LatestCostumes,
	quote: Quote,
	slider: Slider,
	text: Text,
};
