// Code generated by Slice Machine. DO NOT EDIT.

import AboutMeShort from "./AboutMeShort";
import ArticlePreview from "./ArticlePreview";
import ContactForm from "./ContactForm";
import HeadingWithText from "./HeadingWithText";
import Image from "./Image";
import ImageGallery from "./ImageGallery";
import InstagramFeed from "./InstagramFeed";
import Quote from "./Quote";
import Slider from "./Slider";
import Text from "./Text";

export {
  AboutMeShort,
  ArticlePreview,
  ContactForm,
  HeadingWithText,
  Image,
  ImageGallery,
  InstagramFeed,
  Quote,
  Slider,
  Text,
};

export const components = {
  about_me_short: AboutMeShort,
  article_preview: ArticlePreview,
  contact_form: ContactForm,
  heading_with_text: HeadingWithText,
  image: Image,
  image_gallery: ImageGallery,
  instagram_feed: InstagramFeed,
  quote: Quote,
  slider: Slider,
  text: Text,
};
